config/routes.rb
FoosballTracker::Application.routes.draw do
  resources :players, only: [:show, :index]
  resources :matches do
    resources :comments, only: [:create, :destroy]
  end
  resources :rankings, only: [:index]  

  devise_for :player, path: '', path_names: { sign_in: "login", 
                                                    sign_out: "logout", 
                                                    sign_up: "register" } 
  root to: 'static_pages#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :match
	belongs_to :player
  default_scope -> { order(created_at: :desc) }
  validates :player_id, :match_id, presence: true
  validates :content, presence: true, length: { maximum: 300 }
end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :player1, class_name: "Player", foreign_key: "player1_id"
	belongs_to :player2, class_name: "Player", foreign_key: "player2_id"
	has_many :comments, dependent: :destroy

	validates :date, :player1_id, :player2_id, :player1_score, :player2_score, presence: true
	validates :player1_score, :player2_score, numericality: { only_integer: true }
	validates_inclusion_of :player1_score, :player2_score, in: 0..10
	validates_date :date, :before => lambda { Date.tomorrow }

	validate :there_should_be_one_winner
	validate :player1_has_to_be_different_than_player2 	

	def difference_in_goals_index
		difference_in_goals = (player1_score - player2_score).abs
		case difference_in_goals
			when 1
			  return 10
			when 2
			  return 15
			else
			  return (11+difference_in_goals)/0.8
		end
	end

	def difference_in_players_points
		(player1.points-player2.points).abs
	end

	def winning_probability_for(player)
		if player == expected_winner
			1/(10**(-(difference_in_players_points/40.0))+1)
		else
			1-1/(10**(-(difference_in_players_points/40.0))+1)
		end
	end

	def result_for(player)
	 player == actual_winner ? 1 : 0
	end

	def expected_winner
	 player1.points > player2.points ? player1 : player2		
	end

	def actual_winner
		player1_score == 10 ? player1 : player2
	end

	def add_points_to_players
		gained_points = difference_in_goals_index*(result_for(player1) - winning_probability_for(player1))
		player1.update_attribute(:points, player1.points+gained_points)
		gained_points = difference_in_goals_index*(result_for(player2) - winning_probability_for(player2))
		player2.update_attribute(:points, player2.points+gained_points)
	end

	private

	def player1_has_to_be_different_than_player2
 		errors.add(:player2, 'You have to choose two different players') unless player1_id != player2_id
 	end 	

 	def there_should_be_one_winner
 		errors.add(:score1, 'There should be one winner') unless 
 			((player1_score == 10 || player2_score == 10)&&(player1_score+player2_score!=20)) 		
 	end
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :matches, dependent: :destroy
	has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :first_name, :last_name, presence: true
	  
  def number_of_matches
		Match.where(player1: self).count +
		Match.where(player2: self).count
	end

  def total_score
  	Match.where(player1: self).sum(:player1_score)+
	 	Match.where(player2: self).sum(:player2_score)
	end

	def wins		
		Match.where(player1: self, player1_score: 10).count + 			
		Match.where(player2: self, player2_score: 10).count
	end

	def losts
		Match.where(player1: self).where.not(player1_score: 10).count + 			
		Match.where(player2: self).where.not(player2_score: 10).count		
	end

	def average_number_of_goals
		if number_of_matches != 0
			total_score/number_of_matches
		end
	end

	def position_in_classification
		classification = Player.all.sort_by(&:points).reverse
		position = 1
		classification.each do |player|
			return position if player.id == self.id 	
			position = position+1 
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
end           

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_player!, only: [:create, :destroy]
	before_action :correct_player, only: [:destroy]

	def create
		@match = Match.find(params[:match_id])
		@comment = @match.comments.create(comments_params)		
		@comment.player_id = current_player.id
		if @comment.save
			flash[:success] = "Comment created!"
			redirect_to match_path(@match)		
		else			
			redirect_to root_path				
			flash.now[:danger] = "Could not save your comment"
		end
	end

	def destroy
		@comment.destroy
		flash[:success] = "Comment deleted"
		redirect_to request.referrer || root_path
	end

	private
	def comments_params
		params.require(:comment).permit(:content)
	end

	def correct_player
		@comment = current_player.comments.find_by(id: params[:id])
		redirect_to root_path if @comment.nil?
	end

end

app/controllers/matches_controller.rb
require 'will_paginate/array'
class MatchesController < ApplicationController
  before_action :authenticate_player!
  before_action :admin_user, only: [:destroy, :edit, :update]

  def new
  	@match = Match.new
  end

  def create  	  
  	@match = Match.new(matches_params)
    if @match.save
      @match.add_points_to_players
      redirect_to matches_path
    else      
      render action: 'new'
  	end 
  end

  def index
    @matches = Match.all.sort_by(&:date).reverse.paginate(page: params[:page], per_page: 10)
  end

  def destroy
  	@match = Match.find(params[:id])
  	@match.destroy
  	redirect_to matches_path
  end

  def edit
  	@match = Match.find(params[:id])
  end

  def update
  	@match = Match.find(params[:id])	
    if @match.update_attributes(matches_params)
      redirect_to matches_path
    else      
      render action: 'edit'
  	end  	
  end

  def show
    @match = Match.find(params[:id])
    @comments = @match.comments.paginate(page: params[:page], per_page: 8)
  end

  private
  def matches_params
    params.require(:match).permit(:date, :player1_id, :player2_id, 
                                  :player1_score, :player2_score)
  end

  def admin_user
    redirect_to root_path unless current_player.admin
    flash.now[:danger] = 'You have to be an admin to do that'
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_action :authenticate_player!
  def index
    @players = Player.paginate(page: params[:page], :per_page => 15)
  end
  
  def show
  	@player = Player.find(params[:id])
  end
end

app/controllers/rankings_controller.rb
require 'will_paginate/array'
class RankingsController < ApplicationController	
	before_action :authenticate_player!

	def index
    @rankings = Player.all.sort_by(&:points).reverse.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
		redirect_to current_player if current_player
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/player_helper.rb
module PlayerHelper
	def gravatar_for(player, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(player.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: player.first_name, class: "gravatar")
	end
end

app/views/comments/_comment.html.erb
<li>
 	<span class="content">
 		<%= gravatar_for(comment.player, size: 40) %>
		<%= "#{comment.player.last_name}:" %>
	 	<%= comment.content %>
	</span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
			<% if current_player == comment.player %>
				<%= link_to "delete", match_comment_path(comment.match_id, comment), method: :delete,
																data: { confirm: "Are you sure?" } %> 
			<% end %>
	</span>
</li>			

app/views/comments/_comment_form.html.erb
<%= form_for([@match, @match.comments.build]) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Add a comment..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class='container'>
    Foosball Tracker
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Foosball tracker", root_path, id: "logo" %>
    <ul class="nav navbar-nav navbar-right">
        <% if player_signed_in? %>
         <li><%= link_to "Players", players_path %></li>
          <li><%= link_to "Matches", matches_path %></li>
          <li><%= link_to "Ranking", rankings_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_player %></li>
              <li><%= link_to "Settings", edit_player_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", destroy_player_session_path, method: :delete %>
              </li>  
            </ul>
         <% else %>
            <li><%= link_to "Sign up", new_player_registration_path %></li>
            <li><%= link_to "Login", new_player_session_path %></li>
        <% end %>     
      </ul>
    </nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>FoosballTracker</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>   
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  	 <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/matches/edit.html.erb
<h1>Editing match</h1>
<div class='row'>
  <div class="col-md-6 col-md-offset-3">
		<%= form_for @match, url: {action: "update"} do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
			
    	<%= f.label :date %><br />
			<%= f.text_field :date, class: 'form-control' %>
			
			<%= f.label :first_player %><br />
			<%= f.collection_select :player1_id, Player.all.sort_by(&:last_name), 
															:id, :last_name, :include_blank => true %><br />
			<%= f.label :second_name %><br />
			<%= f.collection_select :player2_id, Player.all.sort_by(&:last_name), 
															:id, :last_name, :include_blank => true %><br />

			<%= f.label :first_player_score %><br />
			<%= f.text_field :player1_score, class: 'form-control' %>
			
			<%= f.label :second_player_score %><br />
			<%= f.text_field :player2_score, class: 'form-control' %><br />
			
			<%= f.submit 'Submit', class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/matches/index.html.erb
<h1>Listing matches</h1>
	<ul class='index'>
  	<%= link_to new_match_path, class: 'btn btn-primary btn-lg' do %>
			<span class="glyphicon glyphicon-plus"></span>
			New match
		<% end %>
		
		<% @matches.each do |match| %>
	  	<li>
	  		<%= match.date %> |
	  		<%= link_to "#{ match.player1.last_name } vs #{ match.player2.last_name } | ",						match_path(match) %>
		  	<%= match.player1_score %>:<%= match.player2_score %>	  	
		  	<% if current_player.admin? %>
		  		<%= link_to "Edit", edit_match_path(match) %>
		  		<%= link_to "Destroy", match, method: :delete, data: { confirm: "You're sure?" } %>
		  	<% end %>
		  </li>
		<% end %>
	</ul> 
	<%= will_paginate %>

app/views/matches/new.html.erb
<h1>New match</h1>
<div class='row'>
  <div class="col-md-6 col-md-offset-3">
		<%= form_for @match, url: {action: "create"} do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
			
  	<%= f.label :date %><br />
    <div class="large-12 columns select-date-wrapper">
			<%= f.date_select :date, start_year: 2015, :prompt => { :day => 'Select day', :month => 'Select month', :year => 'Select year'} %>
		</div>			
		
		<%= f.label :first_player %><br />
		<%= f.collection_select :player1_id, Player.all.sort_by(&:last_name), 
														:id, :last_name, :include_blank => true %><br />
		<%= f.label :second_name %><br />
		<%= f.collection_select :player2_id, Player.all.sort_by(&:last_name), 
														:id, :last_name, :include_blank => true %><br />
		
			<%= f.label :first_player_score %><br />
			<%= f.text_field :player1_score, class: 'form-control' %>
			
			<%= f.label :second_player_score %><br />
			<%= f.text_field :player2_score, class: 'form-control' %><br />
			
			<%= f.submit 'Submit', class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/matches/show.html.erb
<div class="row">
	<aside class="col-md-4">
		<ul class="match_info">
			<li><h1>Match #<%= @match.id %></h1></li>
			<li><%= @match.player1.last_name %> vs <%= @match.player2.last_name %> |
			<%= @match.player1_score %>:<%= @match.player2_score %></li>
			<li><%= @match.date %></li>
		</ul>
	</aside>
	<div class="col-md-6">
		<% if @match.comments.any? %>
			<h3>Comments (<%= @match.comments.count %>)</h3>
			<ol class="comments">
				<%= render @comments %>
			</ol>
			<%= will_paginate @comments %>			
		<% end %>
		<%= render 'comments/comment_form' %>		
	</div>	
</div>

app/views/players/index.html.erb
<h1>All players</h1>
	<%= will_paginate %>
	<ul class='index'>
		<% @players.each do |player| %>		
			<li>
				<%= gravatar_for(player) %>
				<%= link_to "#{player.first_name} #{player.last_name}", player %>
			</li>
		<% end %>
	</ul>
	<%= will_paginate %>




    













  

app/views/players/show.html.erb
<div class="row">
   <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @player %>
        <%= @player.first_name %>
        <%= @player.last_name %>
      </h1> 
    </section>
  </aside>  
  <div class="col-md-8">
    <ul class="player_statistics">
      <li>Position in general classification: <%= @player.position_in_classification %>
      <li>Points in general clasification: <%= @player.points %></li><br />
    	<li>Number of matches: <%= @player.number_of_matches %></li>
    	<li>Wins: <%= @player.wins %></li>
    	<li>Losts: <%= @player.losts %></li>    	
    	<li>Goals: <%= @player.total_score %></li>
    	<li>Average number of goals: <%= @player.average_number_of_goals %></li>
    </ul>
  </div>  
</div>

app/views/rankings/index.html.erb
<h1>Ranking</h1>
	<ul class='index'>
		<% @rankings.each do |player| %>  
	    <li>
      <%= gravatar_for(player) %>
      <%= player.position_in_classification %>.
      <%= link_to "#{player.first_name} #{player.last_name}", player %><br>
      <%= player.points %> points
    	</li>		    
	  <% end %>
  <%= will_paginate %>
  </ul>






	

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
    <div class="alert alert-danger">
    	The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
    	<% object.errors.full_messages.each do |msg| %>
    		<li><%= msg %></li>
    	<% end %>
    </ul>
  </div>
  <% end %>

app/views/static_pages/index.html.erb
<div class="center jumbotron">		
	<h1>Welcome in Foosball Tracker!</h1>
	<p><h4>Are you a fan of foosball? Let’s make it easier with our app – create users, organize a match and keep track of scores.</h4></p>
	<p><h4>Play, score and win! Have fun!</h4></p><br>

	<%= link_to "Sign up now!", new_player_registration_path, 
															class: 'btn btn-primary btn-lg' %>	
</div>